In [1]:
import torch
import numpy as np

In [2]:
data_latihan = [[1, 2], [3, 4]]
data_latihan

[[1, 2], [3, 4]]

In [3]:
type(data_latihan)

list

In [4]:
np.array(data_latihan)

array([[1, 2],
       [3, 4]])

In [5]:
np.asarray(data_latihan)

array([[1, 2],
       [3, 4]])

In [6]:
torch.tensor(data_latihan)

tensor([[1, 2],
        [3, 4]])

In [7]:
data_latihan = torch.tensor(data_latihan)

In [8]:
type(data_latihan)

torch.Tensor

In [9]:
data_latihan.dtype

torch.int64

In [10]:
numpy_array = np.random.rand(4, 5)
numpy_array

array([[0.38975623, 0.61437328, 0.09181888, 0.65021015, 0.92061694],
       [0.96771657, 0.16137785, 0.07509909, 0.5049288 , 0.78887783],
       [0.17251954, 0.68101442, 0.79849957, 0.11917003, 0.62011255],
       [0.51019293, 0.65232516, 0.19607938, 0.86967164, 0.59790608]])

In [11]:
torch.from_numpy(numpy_array)

tensor([[0.3898, 0.6144, 0.0918, 0.6502, 0.9206],
        [0.9677, 0.1614, 0.0751, 0.5049, 0.7889],
        [0.1725, 0.6810, 0.7985, 0.1192, 0.6201],
        [0.5102, 0.6523, 0.1961, 0.8697, 0.5979]], dtype=torch.float64)

In [12]:
torch.tensor(numpy_array)

tensor([[0.3898, 0.6144, 0.0918, 0.6502, 0.9206],
        [0.9677, 0.1614, 0.0751, 0.5049, 0.7889],
        [0.1725, 0.6810, 0.7985, 0.1192, 0.6201],
        [0.5102, 0.6523, 0.1961, 0.8697, 0.5979]], dtype=torch.float64)

In [13]:
torch.ones(4, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [14]:
torch.zeros(4, 5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [15]:
torch.randn(6, 6)

tensor([[ 0.0818,  0.3977,  0.6190,  1.5242, -0.2891, -0.7344],
        [-0.9784,  1.2426, -1.9565,  0.0142, -0.9681,  0.0058],
        [ 0.9102, -1.0919,  0.5895, -0.6921, -0.9096, -2.3397],
        [ 1.1315,  0.7776, -2.3078, -0.9426,  1.0359,  0.6967],
        [-0.3280, -0.6245,  0.8051, -0.1414, -0.2814,  0.2945],
        [-0.9492, -0.7653, -0.6132,  0.1896, -0.5439, -2.3637]])

In [16]:
torch.rand(6, 6)

tensor([[0.0965, 0.1646, 0.2118, 0.1889, 0.7892, 0.4663],
        [0.2078, 0.1979, 0.5047, 0.4285, 0.9914, 0.7297],
        [0.3367, 0.4980, 0.6395, 0.7782, 0.5209, 0.3887],
        [0.4921, 0.9278, 0.4546, 0.6824, 0.1632, 0.3711],
        [0.7731, 0.6907, 0.7688, 0.4030, 0.0877, 0.9618],
        [0.0924, 0.6716, 0.2115, 0.5449, 0.8081, 0.9966]])

In [17]:
torch.arange(6)

tensor([0, 1, 2, 3, 4, 5])

In [19]:
torch.Tensor(100)

tensor([1.7753e+28, 1.3458e-14, 4.0099e-11, 6.7884e-07, 4.0046e-11, 2.6854e-06,
        4.0046e-11, 4.2246e-05, 4.0046e-11, 1.7569e-04, 4.0046e-11, 1.0781e-08,
        4.0046e-11, 4.2424e-08, 1.7035e+28, 1.3563e-19, 1.3563e-19, 1.0139e-08,
        2.6179e-12, 2.5348e-09, 2.6321e-12, 6.4890e-07, 2.6035e-12, 1.6223e-07,
        2.5753e-12, 1.6612e-04, 2.5607e-12, 1.0382e-05, 8.2516e+17, 2.0190e-19,
        1.3563e-19, 4.5071e+16, 4.1719e-08, 1.4587e-19, 1.7183e-04, 1.4585e-19,
        4.2417e-08, 1.4587e-19, 1.0918e-05, 1.4586e-19, 1.0546e-08, 1.4588e-19,
        4.2720e-05, 3.1437e-12, 1.3589e-19, 1.3563e-19, 7.9717e-10, 1.0780e-08,
        5.8270e-10, 1.0623e-05, 5.8270e-10, 1.6876e-07, 5.8270e-10, 1.0723e-08,
        5.8270e-10, 4.2420e-08, 5.8270e-10, 2.6659e-09, 1.9406e+17, 1.3563e-19,
        1.3563e-19, 4.0099e-11, 2.6079e-09, 4.0046e-11, 1.0504e-05, 4.0046e-11,
        4.3920e-05, 4.0046e-11, 6.5188e-10, 4.0046e-11, 1.0921e-05, 4.0046e-11,
        4.2251e-05, 1.7035e+28, 1.3563e-

In [20]:
torch.rand(6, 6)

tensor([[0.9860, 0.4980, 0.4241, 0.5063, 0.2277, 0.6774],
        [0.5738, 0.1689, 0.1166, 0.5512, 0.1044, 0.8295],
        [0.3327, 0.6406, 0.6129, 0.5121, 0.6967, 0.0404],
        [0.0749, 0.9867, 0.7710, 0.2708, 0.6939, 0.7745],
        [0.6744, 0.6431, 0.4145, 0.1823, 0.9045, 0.5959],
        [0.4142, 0.7829, 0.5338, 0.5795, 0.9391, 0.3041]])

In [21]:
praktikum_tensor = torch.rand(6, 6)

In [22]:
praktikum_tensor.dtype

torch.float32

In [23]:
praktikum_tensor.device

device(type='cpu')

In [24]:
praktikum_tensor[:, 1:3]

tensor([[0.9042, 0.7062],
        [0.9753, 0.6735],
        [0.0712, 0.0459],
        [0.8238, 0.5852],
        [0.6702, 0.1337],
        [0.6500, 0.4433]])

In [25]:
praktikum_tensor.mul(praktikum_tensor)

tensor([[4.7475e-02, 8.1752e-01, 4.9874e-01, 2.3555e-02, 5.3931e-01, 2.5729e-03],
        [8.9010e-02, 9.5112e-01, 4.5362e-01, 3.0767e-01, 2.7825e-01, 5.1785e-04],
        [8.6555e-02, 5.0742e-03, 2.1041e-03, 4.3268e-01, 4.3722e-02, 8.2826e-01],
        [6.6764e-02, 6.7862e-01, 3.4248e-01, 6.4355e-02, 7.8355e-01, 9.6664e-02],
        [6.7435e-02, 4.4917e-01, 1.7870e-02, 9.7099e-02, 7.7626e-03, 4.7003e-01],
        [1.0690e-01, 4.2251e-01, 1.9652e-01, 9.6243e-01, 3.0870e-02, 7.8007e-02]])

In [26]:
praktikum_tensor*praktikum_tensor

tensor([[4.7475e-02, 8.1752e-01, 4.9874e-01, 2.3555e-02, 5.3931e-01, 2.5729e-03],
        [8.9010e-02, 9.5112e-01, 4.5362e-01, 3.0767e-01, 2.7825e-01, 5.1785e-04],
        [8.6555e-02, 5.0742e-03, 2.1041e-03, 4.3268e-01, 4.3722e-02, 8.2826e-01],
        [6.6764e-02, 6.7862e-01, 3.4248e-01, 6.4355e-02, 7.8355e-01, 9.6664e-02],
        [6.7435e-02, 4.4917e-01, 1.7870e-02, 9.7099e-02, 7.7626e-03, 4.7003e-01],
        [1.0690e-01, 4.2251e-01, 1.9652e-01, 9.6243e-01, 3.0870e-02, 7.8007e-02]])

In [27]:
praktikum_tensor.matmul(praktikum_tensor.T)

tensor([[1.9292, 1.8961, 0.4616, 1.9192, 0.9043, 1.2658],
        [1.8961, 2.0802, 0.6840, 1.8894, 1.0560, 1.6732],
        [0.4616, 0.6840, 1.3984, 0.7965, 0.9776, 1.0991],
        [1.9192, 1.8894, 0.7965, 2.0324, 1.0676, 1.3706],
        [0.9043, 1.0560, 0.9776, 1.0676, 1.1094, 1.0925],
        [1.2658, 1.6732, 1.0991, 1.3706, 1.0925, 1.7972]])

In [28]:
torch.matmul(praktikum_tensor, praktikum_tensor.T)

tensor([[1.9292, 1.8961, 0.4616, 1.9192, 0.9043, 1.2658],
        [1.8961, 2.0802, 0.6840, 1.8894, 1.0560, 1.6732],
        [0.4616, 0.6840, 1.3984, 0.7965, 0.9776, 1.0991],
        [1.9192, 1.8894, 0.7965, 2.0324, 1.0676, 1.3706],
        [0.9043, 1.0560, 0.9776, 1.0676, 1.1094, 1.0925],
        [1.2658, 1.6732, 1.0991, 1.3706, 1.0925, 1.7972]])

In [29]:
praktikum_tensor @ praktikum_tensor.T

tensor([[1.9292, 1.8961, 0.4616, 1.9192, 0.9043, 1.2658],
        [1.8961, 2.0802, 0.6840, 1.8894, 1.0560, 1.6732],
        [0.4616, 0.6840, 1.3984, 0.7965, 0.9776, 1.0991],
        [1.9192, 1.8894, 0.7965, 2.0324, 1.0676, 1.3706],
        [0.9043, 1.0560, 0.9776, 1.0676, 1.1094, 1.0925],
        [1.2658, 1.6732, 1.0991, 1.3706, 1.0925, 1.7972]])

In [30]:
praktikum_tensor.sum(axis=1)

tensor([2.7668, 3.0521, 2.1883, 3.1172, 2.1489, 2.8563])

In [31]:
torch.cat([praktikum_tensor, praktikum_tensor], axis=1)

tensor([[0.2179, 0.9042, 0.7062, 0.1535, 0.7344, 0.0507, 0.2179, 0.9042, 0.7062,
         0.1535, 0.7344, 0.0507],
        [0.2983, 0.9753, 0.6735, 0.5547, 0.5275, 0.0228, 0.2983, 0.9753, 0.6735,
         0.5547, 0.5275, 0.0228],
        [0.2942, 0.0712, 0.0459, 0.6578, 0.2091, 0.9101, 0.2942, 0.0712, 0.0459,
         0.6578, 0.2091, 0.9101],
        [0.2584, 0.8238, 0.5852, 0.2537, 0.8852, 0.3109, 0.2584, 0.8238, 0.5852,
         0.2537, 0.8852, 0.3109],
        [0.2597, 0.6702, 0.1337, 0.3116, 0.0881, 0.6856, 0.2597, 0.6702, 0.1337,
         0.3116, 0.0881, 0.6856],
        [0.3269, 0.6500, 0.4433, 0.9810, 0.1757, 0.2793, 0.3269, 0.6500, 0.4433,
         0.9810, 0.1757, 0.2793]])

In [32]:
torch.cat([praktikum_tensor, praktikum_tensor], axis=0)

tensor([[0.2179, 0.9042, 0.7062, 0.1535, 0.7344, 0.0507],
        [0.2983, 0.9753, 0.6735, 0.5547, 0.5275, 0.0228],
        [0.2942, 0.0712, 0.0459, 0.6578, 0.2091, 0.9101],
        [0.2584, 0.8238, 0.5852, 0.2537, 0.8852, 0.3109],
        [0.2597, 0.6702, 0.1337, 0.3116, 0.0881, 0.6856],
        [0.3269, 0.6500, 0.4433, 0.9810, 0.1757, 0.2793],
        [0.2179, 0.9042, 0.7062, 0.1535, 0.7344, 0.0507],
        [0.2983, 0.9753, 0.6735, 0.5547, 0.5275, 0.0228],
        [0.2942, 0.0712, 0.0459, 0.6578, 0.2091, 0.9101],
        [0.2584, 0.8238, 0.5852, 0.2537, 0.8852, 0.3109],
        [0.2597, 0.6702, 0.1337, 0.3116, 0.0881, 0.6856],
        [0.3269, 0.6500, 0.4433, 0.9810, 0.1757, 0.2793]])

In [33]:
praktikum_tensor.shape

torch.Size([6, 6])

In [34]:
praktikum_tensor.size()

torch.Size([6, 6])

In [35]:
praktikum_tensor.clip(0.5, 0.8)

tensor([[0.5000, 0.8000, 0.7062, 0.5000, 0.7344, 0.5000],
        [0.5000, 0.8000, 0.6735, 0.5547, 0.5275, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.6578, 0.5000, 0.8000],
        [0.5000, 0.8000, 0.5852, 0.5000, 0.8000, 0.5000],
        [0.5000, 0.6702, 0.5000, 0.5000, 0.5000, 0.6856],
        [0.5000, 0.6500, 0.5000, 0.8000, 0.5000, 0.5000]])

In [36]:
praktikum_tensor.cpu().detach().numpy()

array([[0.2178874 , 0.90416616, 0.706216  , 0.15347672, 0.73437864,
        0.05072415],
       [0.29834622, 0.9752556 , 0.673514  , 0.5546838 , 0.5274952 ,
        0.0227564 ],
       [0.2942021 , 0.07123363, 0.04587036, 0.65778077, 0.20909852,
        0.91009027],
       [0.25838667, 0.8237845 , 0.58521676, 0.25368267, 0.8851853 ,
        0.3109085 ],
       [0.25968271, 0.6701985 , 0.13367689, 0.31160754, 0.08810574,
        0.68558484],
       [0.32694912, 0.6500094 , 0.4433046 , 0.9810373 , 0.17569727,
        0.27929753]], dtype=float32)